### ISSUE TITLE
Action space?

### ISSUE THREAD

**Issue by zhaoyingnan179346** [mpSchrader/gym-sokoban#18]
hello!
Thanks for your code so much.I am wondering what's the difference between action 0-3 and action 4-7.I found they have the same consequence in my test.

**Comment by mpSchrader** [comment]
Hi @zhaoyingnan179346,
the difference is that there are move- and push-actions.
Actions 0-3 are pushing actions.
Actions 4-7 are moving actions.

**Moving Actions**:
These actions move the player to an adjacent field, if this is not occupied by a box or wall.

**Pushing actions**:
These actions are also moving the actions, with one difference a box in the way (if it got space to be pushed) it will be pushed and the player follows the box.

Does this answer your question?

Ps: If you like the repo, feel free to star it! :wink:

**Comment by zhaoyingnan179346** [comment]
Thank you for your reply.But I still can't figure it out. I found if there is a box to the left of the agent, Action 2 and Action 6 can both push it(The box got space to be pushed). Action 0 and action 4 both can move the player to up(this is not occupied by a box). In a word, I found that Moving actions can push the box when there is a box near the agent, Pushing actions can also move the player when there is no box or wall near the player.Is that right?

**Comment by mpSchrader** [comment]
Are you sure? Because I just checked it on the [lastet commit](https://github.com/mpSchrader/gym-sokoban/commit/b7f996eec95207163ed8e36aba70fcaa60d00c72) on master and everything works as it is supposed to be. 

Yes, pushing will also move the player with or without a box. But moving will never push a box.

**Comment by mpSchrader** [comment]
Here you find an example.

In the first image you see the base situation.
![sokoban_base](https://user-images.githubusercontent.com/9392926/45175204-20d5c680-b20d-11e8-9e0a-b9412deae583.png)

Next a move right action is performed and nothing changes in the environment, because a move action can not push boxes.
![sokoban_move_right_no_change](https://user-images.githubusercontent.com/9392926/45175205-20d5c680-b20d-11e8-904a-d72cdfe223bd.png)

But the push action performed now, move the user and the corresponding box.
![sokoban_push_right](https://user-images.githubusercontent.com/9392926/45175206-20d5c680-b20d-11e8-86b8-2099de154dfd.png)

**Comment by zhaoyingnan179346** [comment]
Yeah,my bad. Thanks a lot.

**Comment by mpSchrader** [comment]
No worries! In case you got any questions! Just open a new issue.

I will close this one, but if you still got a question regarding this, feel free to reopen it!
