### ISSUE TITLE
environment reward for each step

### ISSUE THREAD

**Issue by wrongbattery** [mpSchrader/gym-sokoban#27]
i read your code and i found that reward = -0.1 + sum_component_rewards. So instead of return 1 for Push Box on Target, env returns 0.9 and instead of return 10 for winning, env  returns -0.1+1+10= 10.9

**Comment by mpSchrader** [comment]
Hi @wrongbattery,
First of all thank you for your issue. This is calculated like that, because:
- Every step gets a penalty, independt of other penalties.
- Every box pushed on a target gets a positive reward, no matter what else happens during that step.
- Same goes for the winning reward.

These are not mutually exclusive. Otherwise you would e.g. ignore the reward for the final box pushed on the target to win the game. Therefore it is correct to give a reward of 0.9 every time a box is pushed and in addition the 10 points for winning, if it has been the final box.
Do you agree? If not, please explain why!

Beste Grüße,
Max-Philipp Schrader

E-Mail maxphilipp.schrader@hotmail.de
Mobil +49 1577 2941073
LinkedIn /in/max-philipp-schrader/
Github /mpSchrader



________________________________

**Comment by mpSchrader** [comment]
@wrongbattery Can you confirm that this makes sense to you? :-)

**Comment by mpSchrader** [comment]
I will close this issue. If you want to discuss this further just reopen the issue.
